In [7]:
import pickle
import pandas as pd
import numpy as np
from sklearn import linear_model


In [9]:
df=pd.read_csv('homeprice.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [11]:
model = linear_model.LinearRegression()
model.fit(df[['area']],df.price)

LinearRegression()

In [12]:
model.coef_

array([135.78767123])

In [13]:
model.intercept_

180616.43835616432

In [14]:
model.predict([[5000]])

/home/menge/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

NameError: name 'model' is not defined

### Save Model To a File Using Python Pickle

In [15]:
import pickle

In [16]:
with open('model_pickle','wb') as f:
    pickle.dump(model,f)

Load Saved Model

In [17]:
with open('model_pickle','rb') as file:
    mb=pickle.load(file)

In [18]:
mb.coef_

array([135.78767123])

In [19]:
mb.intercept_

180616.43835616432

In [20]:
mb.predict([[5000]])

/home/menge/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])

### Save Trained Model Using joblib

In [23]:
import joblib

In [24]:
joblib.dump(model, 'model_joblib')

['model_joblib']

 Load Saved Model

In [25]:
mj = joblib.load('model_joblib')

In [26]:
mj.coef_

array([135.78767123])

In [27]:
mj.intercept_

180616.43835616432

In [28]:
mj.predict([[5000]])

/home/menge/anaconda3/lib/python3.11/site-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([859554.79452055])